spring:
  datasource:
    url: jdbc:mysql://localhost:3309/labs
    username: my_user
    password: password123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8380
